#!/bin/bash

# Reference:
# https://gist.github.com/bradoaks/940616
# https://github.com/magnific0/wondershaper/blob/master/wondershaper
# http://linux-ip.net/articles/hfsc.en/ 

ifin=eth0
ifout=wlan0
dlimit=256kbit
limit=1024kbit
dmax=30ms
subnet=192.168.1
ipstart=100
ipend=199

# Clean out previous qdiscs
tc qdisc del dev $ifin root 2> /dev/null
tc qdisc del dev $ifout root 2> /dev/null

# Root qdiscs
tc qdisc add dev $ifout root handle 1: hfsc default 999
tc qdisc add dev $ifin  root handle 1: hfsc default 999

# Default classes. Should only matter outside of expected IP range
tc class add dev $ifout parent 1: classid 1:999 \
   hfsc sc umax 1540b dmax $dmax rate $dlimit ul rate $dlimit
tc class add dev $ifin parent 1: classid 1:999 \
   hfsc sc umax 1540b dmax $dmax rate $dlimit ul rate $dlimit

for i in $( seq $ipstart $ipend )
do
  ip=$subnet.$i

  echo "Adding rules for $ip"

  for iface in $ifin $ifout
  do
    # Primary user flow
    tc class add dev $iface parent 1: classid 1:${i}1 \
       hfsc sc umax 1540b dmax $dmax rate $limit ul rate $limit
    tc qdisc add dev $iface parent 1:${i}1 handle ${i}1 sfq
    # Small packet user flow
    tc class add dev $iface parent 1: classid 1:${i}2 \
       hfsc sc umax 1540b dmax $dmax rate 128kbit ul rate 128kbit
    tc qdisc add dev $iface parent 1:${i}2 handle ${i}2 sfq
    # Packet length less than 256
    tc filter add dev $iface parent 1: \
       protocol ip prio 1 u32 match u16 0x0000 0xff00 at 2
  done
  tc filter add dev $ifout parent 1: \
     protocol ip prio 1 u32 match ip src $ip/32 flowid 1:${i}1
  tc filter add dev $ifin parent 1: \
     protocol ip prio 1 u32 match ip dst $ip/32 flowid 1:${i}1
done
